# Generated by Django 4.1.5 on 2023-01-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerstatistics',
            name='add_cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerstatistics',
            name='add_wish_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerstatistics',
            name='bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerstatistics',
            name='remove_cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerstatistics',
            name='remove_wish_list',
            field=models.IntegerField(default=0),
        ),
    ]
