version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    environment:
      - DEBUG=0
      - SECRET_KEY=change_me
      - DJANGO_ALLOWED_HOSTS=164.90.190.249 localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_PORT=5432
      - SQL_HOST=db
      - DATABASE=postgres
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: