# Generated by Django 4.1.5 on 2023-01-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
    ]
