# Generated by Django 4.1.5 on 2023-01-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_reviewimages_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimages',
            name='review_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.review'),
        ),
    ]
