# Generated by Django 4.1.5 on 2023-01-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_reviewimages_review_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('date',), 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterModelOptions(
            name='reviewimages',
            options={'verbose_name': 'ReviewImages', 'verbose_name_plural': 'ReviewImages'},
        ),
        migrations.AlterField(
            model_name='reviewimages',
            name='img',
            field=models.FileField(upload_to='review_images/'),
        ),
    ]
