# Generated by Django 4.1.5 on 2023-01-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_review_options_alter_reviewimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimages',
            name='img',
            field=models.ImageField(upload_to='review_images/'),
        ),
    ]
