# Generated by Django 4.1.5 on 2023-01-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_reviewimages_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='pr_slug',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='reviewimages',
            old_name='pr_slug',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='reviewimages',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
