# Generated by Django 4.1.5 on 2023-01-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_pr_slug_review_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimages',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='review_img',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.reviewimages'),
        ),
    ]
