# Generated by Django 4.1.5 on 2023-01-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_reviewimages_review_id_review_review_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_img',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.reviewimages'),
        ),
    ]
