# Generated by Django 4.1.5 on 2023-01-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_review_review_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='pr_slug',
        ),
        migrations.RenameField(
            model_name='reviewimages',
            old_name='product',
            new_name='pr_slug',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_img',
        ),
        migrations.AddField(
            model_name='reviewimages',
            name='review_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.review'),
        ),
    ]
