# Generated by Django 4.1.5 on 2023-01-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
