# Generated by Django 4.1.5 on 2023-01-18 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_orders_product_ordersitem_orders_ordersitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='OrdersItem',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.DeleteModel(
            name='OrdersItem',
        ),
    ]
