# Generated by Django 4.1.5 on 2023-01-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_orders_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalarea',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='personalarea',
            old_name='street',
            new_name='phone',
        ),
    ]
