# Generated by Django 4.1.5 on 2023-01-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_cart_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersitem',
            options={'verbose_name': 'Order_Item', 'verbose_name_plural': 'Order_Items'},
        ),
        migrations.AlterModelOptions(
            name='personalarea',
            options={'verbose_name': 'Personal_Area', 'verbose_name_plural': 'Personal_Areas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('date',), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='reviewimages',
            options={'verbose_name': 'Review_Image', 'verbose_name_plural': 'Review_Images'},
        ),
    ]
