# Generated by Django 4.1.5 on 2023-01-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('assembl', 'В сборке у продавца'), ('delivery', 'В доставке'), ('received', 'Получен')], default='assembl', max_length=30),
        ),
    ]
