# Generated by Django 4.1.5 on 2023-01-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_personalarea_email_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalarea',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
