# Generated by Django 4.1.5 on 2023-01-22 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0036_personalarea_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalarea',
            name='your_products',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
