# Generated by Django 4.1.5 on 2023-01-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_personalarea_all_earned_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalarea',
            name='all_earned_money',
            field=models.IntegerField(default=0),
        ),
    ]
