# Generated by Django 4.1.5 on 2023-01-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_personalarea_all_earned_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalarea',
            name='all_earned_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
