# Generated by Django 4.1.5 on 2023-01-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_personalarea_all_earned_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalarea',
            name='email',
            field=models.EmailField(default='ex@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='personalarea',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalarea',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
