# Generated by Django 4.1.5 on 2023-01-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_personalarea_email_personalarea_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalarea',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
