# Generated by Django 4.1.5 on 2023-01-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_personalarea_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalarea',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalarea',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
