# Generated by Django 4.1.5 on 2023-01-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_personalarea_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalarea',
            name='email',
        ),
    ]
