# Generated by Django 4.1.5 on 2023-01-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_remove_personalarea_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalarea',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalarea',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/avatars/'),
        ),
        migrations.AlterField(
            model_name='personalarea',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalarea',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalarea',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personalarea',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
