# Generated by Django 4.1.5 on 2023-01-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_alter_personalarea_address_alter_personalarea_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalarea',
            name='your_products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
