# Generated by Django 4.1.5 on 2023-01-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_reviewseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalarea',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
