# Generated by Django 4.1.5 on 2023-01-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_alter_reviewseller_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewseller',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=10),
        ),
    ]
