# Generated by Django 4.1.5 on 2023-01-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_remove_wishlist_product_remove_wishlist_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewImages',
        ),
    ]
