# Generated by Django 4.1.5 on 2023-01-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_alter_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='promo_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='promo_use',
        ),
    ]
